FROM debian:12-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget ca-certificates gnupg postgresql-client curl \
    locales \
    && wget https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.0+debian12_all.deb \
    && dpkg -i zabbix-release_latest_7.0+debian12_all.deb \
    && apt-get update && apt-get install -y --no-install-recommends \
    zabbix-server-pgsql \
    zabbix-frontend-php \
    php8.2-pgsql \
    zabbix-nginx-conf \
    zabbix-sql-scripts \
    zabbix-agent2 \
    nginx \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 10051 80 10050

ENTRYPOINT ["/entrypoint.sh"]