# colocar arquivo em /etc/nginx/conf.d/

server {
    listen 8080;
    server_name localhost;
    root /var/www/html/poetas;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}